#!/bin/bash
: "${CLIENT_PROFILE:=fsa}"
: "${API_SERVICE_URL:=https://fsa-dev-cat.epimorphics.net}"
: "${RUN_VARS:=--detach --publish}"

# Check if the script is being run in a Git repository
if ! git rev-parse --is-inside-work-tree &>/dev/null; then
  printf '\n\033[0;31mThis script must be run inside a Git repository.\033[0m\n'
  exit 1
fi

# Check if Docker is installed and running
if ! command -v docker &>/dev/null; then
  printf '\n\033[0;31mDocker is not installed or not running. Please check Docker and try again.\033[0m\n'
  exit 1
else
  DOCKER_SERVER_VERSION=$(docker version --format '{{.Server.Version}}' 2>/dev/null)
  if [ -n "$DOCKER_SERVER_VERSION" ]; then
    printf "\n\033[0;32mDocker is installed and running (version: ${DOCKER_SERVER_VERSION}). Proceeding with the checks... 🎉\033[0m\n"
  else
    printf '\n\033[0;31mDocker is installed but not running, or unable to determine version. Please start Docker and try again.\033[0m\n'
  fi
fi

# The branch prefixes are defined in the list variable and can be modified as needed.
list="issue spike task"
# The list is converted to a regular expression
listRE="^($(printf '%s\n' "$list" | tr ' ' '|'))/"
# Set the branch name based on the current branch
BRANCH_NAME=$(git branch --show-current | grep -E "$listRE" | sed 's/* //')
printf '\n\033[0;105mChecking "%s"... \033[0m\n' "$BRANCH_NAME"
# If the branch name is one of the specified prefixes, skip the checks and exit
if echo "$BRANCH_NAME" | grep -Eq '^(hotfix|rebase|production)'; then
 	printf '\n\033[0;32mNo checks necessary on "%s", skipping hooks... 🎉\033[0m\n' "$BRANCH_NAME"
	exit 0
fi

# Skip hook if every staged files are only markdown (.md) files
files=$(git diff --cached --name-only)
files_to_check=$(echo "$files" | grep '\.md$')
if [ -n "$files_to_check" ] && [ -z "$(echo "$files" | grep -v '\.md$')" ]; then
  printf '\n\033[0;32mOnly markdown files staged (%s), skipping hook.\033[0m\n' "$files_to_check"
  exit 0
fi

# Check there aren't any unstaged changes or an out-of-date index
if ! git update-index -q --ignore-submodules --refresh; then
	printf '\n\033[0;31mUp-to-date check failed😖\033[0m\n'
  DOCKER_BUILD_EXIT_CODE=1
else
  printf '\n\033[0;33mBuilding Docker image with "%s" profile... \033[0m\n' "$CLIENT_PROFILE"
  AWS_PROFILE=$CLIENT_PROFILE make image
  DOCKER_BUILD_EXIT_CODE=$?
fi

# If the Docker image build fails, print an error message and exit with a non-zero error code.
if [ $DOCKER_BUILD_EXIT_CODE -ne 0 ]; then
  printf '\n\033[0;31mDocker image build failed. Please check your changes. 😖\033[0m\n'
  exit 1
fi

# As the Docker image build succeeded then run the image
printf '\n\033[0;32mDocker image build succeeded. 🎉\033[0m\n'
CONTAINER_ID=$(make name)
printf '\n\033[0;33mRunning Docker image %s ... \033[0m\n' "$CONTAINER_ID"
AWS_PROFILE=$CLIENT_PROFILE API_SERVICE_URL=$API_SERVICE_URL RUN_VARS=$RUN_VARS make run

# Wait 5 seconds for the container to be ready and running
secs=5
while [ $secs -gt -1 ]; do
  echo -ne "$secs\033[0K\r"
  sleep 1
  : $((secs--))
done

# Check if the Docker container is still running via docker inspect
docker inspect --format="{{.State.Running}}" "$CONTAINER_ID" | grep 'true' -q
DOCKER_RUN_EXIT_CODE=$?
printf '\n\033[0;33mStopping Docker image with exit code %s ... \033[0m\n' "$DOCKER_RUN_EXIT_CODE"
make stop

if [ $DOCKER_RUN_EXIT_CODE -ne 0 ]; then
  printf '\n\033[0;31mDocker image run failed. Please check your changes. 😖\033[0m\n'
  exit 1
else
  printf '\n\033[0;32mDocker image run succeeded. 🎉\033[0m\n'
  exit 0
fi
